---
- name: "Copy tar file"
  unarchive:
    src: artifact.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: Executing node
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start